### ISSUE TITLE
JQuery field ID requires escaping square brackets

### ISSUE THREAD

**Issue by ghost** [snapshotpl/ZfSnapJquery#1]
When building forms with fieldsets in ZF2, the ID of the fields are set to format "fieldset[fieldname]" - the inline script generation doesn't escape the square brackets and the form element doesn't work.

Temp fix with and addition at line 55 of ZfSnapJquery\Form\View\Helper\AbsractHelper.php

$id = str_replace(']','\]',str_replace('[','\[',$id));

Not the nicest but it works.

**Comment by snapshotpl** [comment]
@cmhunt check my solution

**Comment by ghost** [comment]
Much nicer than my quick fix solution - thanks.
