### ISSUE TITLE
autocomplete to get id => description

### ISSUE THREAD

**Issue by matiasiglesias** [snapshotpl/ZfSnapJquery#3]
do you know how to complete a Autocomplete element with id => description returned as JSON?

**Comment by webdevilopers** [comment]
Can you specify some details on your question @matiasiglesias ? What do you mean by `id => description returned`?

I can only guess that you are trying to custom define your JSON.
Normally you would use `id` and `value` as names e.g.:
http://jqueryui.com/autocomplete/#remote

``` javascript
 $( "#birds" ).autocomplete({
source: "search.php",
minLength: 2,
select: function( event, ui ) {
log( ui.item ?
"Selected: " + ui.item.value + " aka " + ui.item.id :
"Nothing selected, input was " + this.value );
}
});
```

But you can choose any name. As long as you integrate them into your javascript source and add it to JSON on your server side. E.g. I added a `label`:

``` php
        $branchesResults = array();
        foreach ($branches as $branch) {
            $branchesResults[] = array(
                'value' => $branch->getId(),
                'label' => $branch->getCompany()->getName() . ', ' . $branch->getName()
            );
        }
```

**Comment by matiasiglesias** [comment]
webdevilopers thanks for your response. Indeed I used your help.
This is what I do:

On my Form:

```
    $this->add(array(
        'name' => 'search_result',
        'type' => 'Hidden',
        'attributes' => array(
            'id' => 'search_result',
        ),
    ));

    $this->add(array(
        'name' => 'search_term',
        'type' => 'ZfSnapJquery\Form\Element\Autocomplete',
        'options' => array(
            'label' => 'Search Term',
        ),
        'attributes' => array(
            'id' => 'search_term',
            'jquery' => array(
                'source' => array(
                    array('label' => 'foo', 'value' => '1'),
                    array('label' => 'bar', 'value' => '2'),
                    array('label' => 'baz', 'value' => '3')
                ),
                'select' => new \Zend\Json\Expr('function( event, ui ) { $( this ).val( ui.item.label ); $("#search_result").val( ui.item.id ); return false; }'),
            )
        ),
    ));
```

You can also set a Controller Action as source. Term is send via GET under keyword term. So you can do:
'source' => '/route/to/your/action'

and in you controller return a JSON response

public function ReturnJSONResponseAction() {
        $term = $this->params()->fromQuery('term');

```
    return new JsonModel(array(
        array('label' => 'foo', 'value' => $term . '1'),
        array('label' => 'bar', 'value' => $term . '2'),
        'success'=>false,
    ));
```

}

This is where I got help also: http://akrabat.com/zend-framework-2/returning-json-from-a-zf2-controller-action/
